my_robot_joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 30

my_robot_head_controller:
  type: "effort_controllers/JointPositionController"
  joint: body_to_head
  pid: {p: 60.0, i: 15.0, d: 15.0}

my_robot_body_to_right_shoulder_controller:
  type: "effort_controllers/JointPositionController"
  joint: body_to_right_shoulder
  pid: {p: 60.0, i: 15.0, d: 15.0}

my_robot_right_shoulder_to_right_up_arm_controller:
  type: "effort_controllers/JointPositionController"
  joint: right_shoulder_to_right_up_arm
  pid: {p: 60.0, i: 15.0, d: 15.0}

my_robot_right_up_arm_to_right_down_arm_controller:
  type: "effort_controllers/JointPositionController"
  joint: right_up_arm_to_right_down_arm
  pid: {p: 60.0, i: 15.0, d: 15.0}

my_robot_body_to_left_shoulder_controller:
  type: "effort_controllers/JointPositionController"
  joint: body_to_left_shoulder
  pid: {p: 60.0, i: 15.0, d: 15.0}

my_robot_left_shoulder_to_left_up_arm_controller:
  type: "effort_controllers/JointPositionController"
  joint: left_shoulder_to_left_up_arm
  pid: {p: 60.0, i: 15.0, d: 15.0}

my_robot_left_up_arm_to_left_down_arm_controller:
  type: "effort_controllers/JointPositionController"
  joint: left_up_arm_to_left_down_arm
  pid: {p: 60.0, i: 15.0, d: 15.0}

my_robot_body_to_right_leg_joint_controller:
  type: "effort_controllers/JointPositionController"
  joint: body_to_right_leg_joint
  pid: {p: 60.0, i: 15.0, d: 15.0}

my_robot_right_leg_joint_to_right_up_leg_controller:
  type: "effort_controllers/JointPositionController"
  joint: right_leg_joint_to_right_up_leg
  pid: {p: 60.0, i: 15.0, d: 15.0}

my_robot_right_up_leg_to_right_down_leg_controller:
  type: "effort_controllers/JointPositionController"
  joint: right_up_leg_to_right_down_leg
  pid: {p: 60.0, i: 15.0, d: 15.0}

my_robot_right_down_leg_to_right_foot_controller:
  type: "effort_controllers/JointPositionController"
  joint: right_down_leg_to_right_foot
  pid: {p: 60.0, i: 15.0, d: 15.0}

my_robot_body_to_left_leg_joint_controller:
  type: "effort_controllers/JointPositionController"
  joint: body_to_left_leg_joint
  pid: {p: 60.0, i: 15.0, d: 15.0}

my_robot_left_leg_joint_to_left_up_leg_controller:
  type: "effort_controllers/JointPositionController"
  joint: left_leg_joint_to_left_up_leg
  pid: {p: 60.0, i: 15.0, d: 15.0}

my_robot_left_up_leg_to_left_down_leg_controller:
  type: "effort_controllers/JointPositionController"
  joint: left_up_leg_to_left_down_leg
  pid: {p: 60.0, i: 15.0, d: 15.0}

my_robot_left_down_leg_to_left_foot_controller:
  type: "effort_controllers/JointPositionController"
  joint: left_down_leg_to_left_foot
  pid: {p: 60.0, i: 15.0, d: 15.0}

